[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning:cached_property.*
    ignore::DeprecationWarning:eth_tester.*
    ignore::DeprecationWarning:web3.*
    ignore::DeprecationWarning:asyncio.*
